name: prology_linux
description: "PROLOGY Flutter Linux - Full implementation based on APK analysis"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_blue_plus: ^1.32.0
  hex: ^0.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
